import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/baslinereporting">BaslineReporting</Link>
        </li>
        <li>
          <Link to="/adhocreporting">AdhocReporting</Link>
        </li>
        <li>
          <Link to="/automatedemailsending">AutomatedEmailSending</Link>
        </li>
        <li>
          <Link to="/customisedorderstatus">CustomisedOrderStatus</Link>
        </li>
        <li>
          <Link to="/audiomusic">AudioMusic</Link>
        </li>
        <li>
          <Link to="/multiplegesturerecogniser">MultipleGestureRecogniser</Link>
        </li>
        <li>
          <Link to="/collecttransactionfees">CollectTransactionFees</Link>
        </li>
        <li>
          <Link to="/demoaccount">DemoAccount</Link>
        </li>
        <li>
          <Link to="/multiplayersupport">MultiplayerSupport</Link>
        </li>
        <li>
          <Link to="/expensetracking">ExpenseTracking</Link>
        </li>
        <li>
          <Link to="/qrcode">QRCode</Link>
        </li>
        <li>
          <Link to="/cardconnectintegration">CardconnectIntegration</Link>
        </li>
        <li>
          <Link to="/graphicalcharts">GraphicalCharts</Link>
        </li>
        <li>
          <Link to="/projectstracking">ProjectsTracking</Link>
        </li>
        <li>
          <Link to="/inventorytrendanalysis">InventoryTrendAnalysis</Link>
        </li>
        <li>
          <Link to="/loyaltysystem">LoyaltySystem</Link>
        </li>
        <li>
          <Link to="/taskblocker">TaskBlocker</Link>
        </li>
        <li>
          <Link to="/rolespermissions">RolesPermissions</Link>
        </li>
        <li>
          <Link to="/usageinsights">UsageInsights</Link>
        </li>
        <li>
          <Link to="/quotemanagement">QuoteManagement</Link>
        </li>
        <li>
          <Link to="/salesreporting">SalesReporting</Link>
        </li>
        <li>
          <Link to="/performancetracker">PerformanceTracker</Link>
        </li>
        <li>
          <Link to="/passcodelock">PasscodeLock</Link>
        </li>
        <li>
          <Link to="/facebooksignin">FacebookSignin</Link>
        </li>
        <li>
          <Link to="/fanwall">FanWall</Link>
        </li>
        <li>
          <Link to="/followers">Followers</Link>
        </li>
        <li>
          <Link to="/testimonials">Testimonials</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
